In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

**Project Details:**

The market research team at AeroFit wants to identify the characteristics of the target
audience for each type of treadmill oAered by the company, to provide a better
recommendation of the treadmills to new customers. The team decides to investigate
whether there are diAerences across the product with respect to customer
characteristics.

**Practicalities:**

Analyse the provided data and provide insights to the best of your abilities. Include the
relevant tables/graphs/visualization to explain what you have learned about the data.

You may structure your EDA/Business Analysis according to these steps:  

**1. Data Exploration and Processing:**
 - Importing data
 - Reading dataframe
 - Check the shape of the dataframe
 - Datatype of each column
 - Missing value detection
 - Checking duplicate values in the dataset

# **Importing the data from the file and reading the DataFrame**

We will import the data from the excel file using the `read_csv()` function and displayed the data

In [3]:
treadmill_df = pd.read_csv('aerofit_treadmill_data.csv')
treadmill_df

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
0,KP281,18,Male,14,Single,3,4,29562,112
1,KP281,19,Male,15,Single,2,3,31836,75
2,KP281,19,Female,14,Partnered,4,3,30699,66
3,KP281,19,Male,12,Single,3,3,32973,85
4,KP281,20,Male,13,Partnered,4,2,35247,47
...,...,...,...,...,...,...,...,...,...
175,KP781,40,Male,21,Single,6,5,83416,200
176,KP781,42,Male,18,Single,5,4,89641,200
177,KP781,45,Male,16,Single,5,5,90886,160
178,KP781,47,Male,18,Partnered,4,5,104581,120
179,KP781,48,Male,18,Partnered,4,5,95508,180

# **Checking the dimensions of the Table imported from the Excel file**

The table imported contains 180 rows and 9 columns by using the `shape` function

In [4]:
treadmill_df.shape

(180, 9)

# **Checking the datatype of each column present in the data**

In [5]:
treadmill_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product        180 non-null    object
 1   Age            180 non-null    int64
 2   Gender         180 non-null    object
 3   Education      180 non-null    int64
 4   MaritalStatus  180 non-null    object
 5   Usage          180 non-null    int64
 6   Fitness        180 non-null    int64
 7   Income         180 non-null    int64
 8   Miles          180 non-null    int64
dtypes: int64(6), object(3)
memory usage: 12.8+ KB

After checking the datatype of each column using the `info()` function we also have witnessed that there are no null or missing values in the data so we don't need to impute any data

# **Check the total no. of duplicate rows, remove them and also reset the index.**

- First we will check the total number of duplicates preent in the dataset using the `duplicated()` function.
- Now we will drop the duplicates using the `drop_duplicates()` function from the dataset.
- And now we will reset index using the function `reset_index(drop=True, inplace=True)` where:
    1. `drop`: If True, drops the old index instead of adding it as a column.
    2. `inplace`: If True, modifies the DataFrame in place.

In [6]:
treadmill_df.duplicated().sum() # This statement will provide us with the duplicated rows in the dataset

0

After checking for the duplicated, by using the `duplicated()` function it returns the value 0 which clears that there are no duplicates present in the data.

# **2. Statistical Summary:**
 Provide an analysis of the statistical summary in few lines for both categorical and
 numerical features.

In [8]:
treadmill_df.describe(include = "all")

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
count,180,180.000000,180,180.000000,180,180.000000,180.000000,180.000000,180.000000
unique,3,NaN,2,NaN,2,NaN,NaN,NaN,NaN
top,KP281,NaN,Male,NaN,Partnered,NaN,NaN,NaN,NaN
freq,80,NaN,104,NaN,107,NaN,NaN,NaN,NaN
mean,NaN,28.788889,NaN,15.572222,NaN,3.455556,3.311111,53719.577778,103.194444
std,NaN,6.943498,NaN,1.617055,NaN,1.084797,0.958869,16506.684226,51.863605
min,NaN,18.000000,NaN,12.000000,NaN,2.000000,1.000000,29562.000000,21.000000
25%,NaN,24.000000,NaN,14.000000,NaN,3.000000,3.000000,44058.750000,66.000000
50%,NaN,26.000000,NaN,16.000000,NaN,3.000000,3.000000,50596.500000,94.000000
75%,NaN,33.000000,NaN,16.000000,NaN,4.000000,4.000000,58668.000000,114.750000
max,NaN,50.000000,NaN,21.000000,NaN,7.000000,5.000000,104581.000000,360.000000